/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_IO_LIBRALINK_CLIENT_PAYMENT_PROTO_LIBRALINK_PB_H_INCLUDED
#define PB_IO_LIBRALINK_CLIENT_PAYMENT_PROTO_LIBRALINK_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _io_libralink_client_payment_proto_SignatureReason {
    io_libralink_client_payment_proto_SignatureReason_NONE = 0,
    io_libralink_client_payment_proto_SignatureReason_IDENTITY = 1,
    io_libralink_client_payment_proto_SignatureReason_FEE_LOCK = 2,
    io_libralink_client_payment_proto_SignatureReason_CONFIRM = 3
} io_libralink_client_payment_proto_SignatureReason;

/* Struct definitions */
typedef struct _io_libralink_client_payment_proto_EnvelopeContent {
    pb_callback_t address;
    pb_callback_t pubKey;
    pb_callback_t algorithm; /* e.g., "secp256k1", "Dilithium5" */
    pb_callback_t reason;
    pb_size_t which_entity;
    union {
        pb_callback_t envelope;
        pb_callback_t errorResponse;
        pb_callback_t processingFee;
        pb_callback_t surchargeRequest;
        pb_callback_t paymentRequest;
        pb_callback_t check;
        pb_callback_t getBalanceRequest;
        pb_callback_t getBalanceResponse;
        pb_callback_t depositRequest;
        pb_callback_t depositResponse;
        pb_callback_t getProcessorsRequest;
        pb_callback_t getProcessorsResponse;
        pb_callback_t registerKeyRequest;
        pb_callback_t registerKeyResponse;
        pb_callback_t sharePayerDetails;
    } entity;
} io_libralink_client_payment_proto_EnvelopeContent;

typedef struct _io_libralink_client_payment_proto_Envelope {
    pb_callback_t id;
    bool has_content;
    io_libralink_client_payment_proto_EnvelopeContent content;
    pb_callback_t sig;
} io_libralink_client_payment_proto_Envelope;

typedef struct _io_libralink_client_payment_proto_ProcessingFee {
    pb_callback_t feeType; /* e.g., FLAT, PERCENT */
    pb_callback_t amount; /* BigDecimal as string */
    pb_callback_t intermediary;
    bool has_envelope;
    io_libralink_client_payment_proto_Envelope envelope;
} io_libralink_client_payment_proto_ProcessingFee;

typedef struct _io_libralink_client_payment_proto_PaymentRequest {
    pb_callback_t amount;
    pb_callback_t from;
    pb_callback_t fromProc;
    pb_callback_t to;
    pb_callback_t toProc;
    pb_callback_t currency;
    int64_t created_at;
    pb_callback_t note;
    pb_callback_t correlationId;
} io_libralink_client_payment_proto_PaymentRequest;

typedef struct _io_libralink_client_payment_proto_SurchargeRequest {
    pb_callback_t amount;
    pb_callback_t to;
    pb_callback_t toProc;
    pb_callback_t note;
    bool has_envelope;
    io_libralink_client_payment_proto_Envelope envelope;
} io_libralink_client_payment_proto_SurchargeRequest;

typedef struct _io_libralink_client_payment_proto_ECheckSplit {
    pb_callback_t amount;
    pb_callback_t to;
    pb_callback_t toProc;
} io_libralink_client_payment_proto_ECheckSplit;

typedef struct _io_libralink_client_payment_proto_ECheck {
    pb_callback_t faceAmount;
    pb_callback_t currency;
    pb_callback_t from;
    pb_callback_t fromProc;
    pb_callback_t to;
    pb_callback_t toProc;
    pb_callback_t splits;
    int64_t createdAt;
    int64_t expiresAt;
    pb_callback_t note;
    pb_callback_t correlationId;
} io_libralink_client_payment_proto_ECheck;

typedef struct _io_libralink_client_payment_proto_GetBalanceRequest {
    pb_callback_t address;
} io_libralink_client_payment_proto_GetBalanceRequest;

typedef struct _io_libralink_client_payment_proto_GetBalanceResponse {
    pb_callback_t address;
    pb_callback_t available;
    pb_callback_t pending;
} io_libralink_client_payment_proto_GetBalanceResponse;

typedef struct _io_libralink_client_payment_proto_DepositRequest {
    bool has_checkEnvelope;
    io_libralink_client_payment_proto_Envelope checkEnvelope;
    pb_callback_t requestEnvelopes;
} io_libralink_client_payment_proto_DepositRequest;

typedef struct _io_libralink_client_payment_proto_DepositResponse {
    pb_callback_t checkEnvelopeId;
    pb_callback_t requestEnvelopeIds;
} io_libralink_client_payment_proto_DepositResponse;

typedef struct _io_libralink_client_payment_proto_RegisterKeyRequest {
    pb_callback_t address;
    pb_callback_t pubKey;
    pb_callback_t algorithm;
    pb_callback_t confirmationId;
    pb_callback_t hash;
} io_libralink_client_payment_proto_RegisterKeyRequest;

typedef struct _io_libralink_client_payment_proto_RegisterKeyResponse {
    pb_callback_t address;
} io_libralink_client_payment_proto_RegisterKeyResponse;

typedef struct _io_libralink_client_payment_proto_GetProcessorsRequest {
    pb_callback_t address;
} io_libralink_client_payment_proto_GetProcessorsRequest;

typedef struct _io_libralink_client_payment_proto_ProcessorDetails {
    pb_callback_t address;
} io_libralink_client_payment_proto_ProcessorDetails;

typedef struct _io_libralink_client_payment_proto_GetProcessorsResponse {
    pb_callback_t processors;
} io_libralink_client_payment_proto_GetProcessorsResponse;

typedef struct _io_libralink_client_payment_proto_ErrorResponse {
    int32_t code;
    pb_callback_t message;
} io_libralink_client_payment_proto_ErrorResponse;

typedef struct _io_libralink_client_payment_proto_SharePayerDetails {
    pb_callback_t challenge;
    pb_callback_t from;
    pb_callback_t fromProc;
} io_libralink_client_payment_proto_SharePayerDetails;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _io_libralink_client_payment_proto_SignatureReason_MIN io_libralink_client_payment_proto_SignatureReason_NONE
#define _io_libralink_client_payment_proto_SignatureReason_MAX io_libralink_client_payment_proto_SignatureReason_CONFIRM
#define _io_libralink_client_payment_proto_SignatureReason_ARRAYSIZE ((io_libralink_client_payment_proto_SignatureReason)(io_libralink_client_payment_proto_SignatureReason_CONFIRM+1))


#define io_libralink_client_payment_proto_EnvelopeContent_reason_ENUMTYPE io_libralink_client_payment_proto_SignatureReason


















/* Initializer values for message structs */
#define io_libralink_client_payment_proto_Envelope_init_default {{{NULL}, NULL}, false, io_libralink_client_payment_proto_EnvelopeContent_init_default, {{NULL}, NULL}}
#define io_libralink_client_payment_proto_EnvelopeContent_init_default {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, 0, {{{NULL}, NULL}}}
#define io_libralink_client_payment_proto_ProcessingFee_init_default {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, false, io_libralink_client_payment_proto_Envelope_init_default}
#define io_libralink_client_payment_proto_PaymentRequest_init_default {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, 0, {{NULL}, NULL}, {{NULL}, NULL}}
#define io_libralink_client_payment_proto_SurchargeRequest_init_default {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, false, io_libralink_client_payment_proto_Envelope_init_default}
#define io_libralink_client_payment_proto_ECheckSplit_init_default {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define io_libralink_client_payment_proto_ECheck_init_default {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, 0, 0, {{NULL}, NULL}, {{NULL}, NULL}}
#define io_libralink_client_payment_proto_GetBalanceRequest_init_default {{{NULL}, NULL}}
#define io_libralink_client_payment_proto_GetBalanceResponse_init_default {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define io_libralink_client_payment_proto_DepositRequest_init_default {false, io_libralink_client_payment_proto_Envelope_init_default, {{NULL}, NULL}}
#define io_libralink_client_payment_proto_DepositResponse_init_default {{{NULL}, NULL}, {{NULL}, NULL}}
#define io_libralink_client_payment_proto_RegisterKeyRequest_init_default {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define io_libralink_client_payment_proto_RegisterKeyResponse_init_default {{{NULL}, NULL}}
#define io_libralink_client_payment_proto_GetProcessorsRequest_init_default {{{NULL}, NULL}}
#define io_libralink_client_payment_proto_ProcessorDetails_init_default {{{NULL}, NULL}}
#define io_libralink_client_payment_proto_GetProcessorsResponse_init_default {{{NULL}, NULL}}
#define io_libralink_client_payment_proto_ErrorResponse_init_default {0, {{NULL}, NULL}}
#define io_libralink_client_payment_proto_SharePayerDetails_init_default {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define io_libralink_client_payment_proto_Envelope_init_zero {{{NULL}, NULL}, false, io_libralink_client_payment_proto_EnvelopeContent_init_zero, {{NULL}, NULL}}
#define io_libralink_client_payment_proto_EnvelopeContent_init_zero {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, 0, {{{NULL}, NULL}}}
#define io_libralink_client_payment_proto_ProcessingFee_init_zero {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, false, io_libralink_client_payment_proto_Envelope_init_zero}
#define io_libralink_client_payment_proto_PaymentRequest_init_zero {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, 0, {{NULL}, NULL}, {{NULL}, NULL}}
#define io_libralink_client_payment_proto_SurchargeRequest_init_zero {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, false, io_libralink_client_payment_proto_Envelope_init_zero}
#define io_libralink_client_payment_proto_ECheckSplit_init_zero {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define io_libralink_client_payment_proto_ECheck_init_zero {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, 0, 0, {{NULL}, NULL}, {{NULL}, NULL}}
#define io_libralink_client_payment_proto_GetBalanceRequest_init_zero {{{NULL}, NULL}}
#define io_libralink_client_payment_proto_GetBalanceResponse_init_zero {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define io_libralink_client_payment_proto_DepositRequest_init_zero {false, io_libralink_client_payment_proto_Envelope_init_zero, {{NULL}, NULL}}
#define io_libralink_client_payment_proto_DepositResponse_init_zero {{{NULL}, NULL}, {{NULL}, NULL}}
#define io_libralink_client_payment_proto_RegisterKeyRequest_init_zero {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define io_libralink_client_payment_proto_RegisterKeyResponse_init_zero {{{NULL}, NULL}}
#define io_libralink_client_payment_proto_GetProcessorsRequest_init_zero {{{NULL}, NULL}}
#define io_libralink_client_payment_proto_ProcessorDetails_init_zero {{{NULL}, NULL}}
#define io_libralink_client_payment_proto_GetProcessorsResponse_init_zero {{{NULL}, NULL}}
#define io_libralink_client_payment_proto_ErrorResponse_init_zero {0, {{NULL}, NULL}}
#define io_libralink_client_payment_proto_SharePayerDetails_init_zero {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define io_libralink_client_payment_proto_EnvelopeContent_address_tag 1
#define io_libralink_client_payment_proto_EnvelopeContent_pubKey_tag 2
#define io_libralink_client_payment_proto_EnvelopeContent_algorithm_tag 3
#define io_libralink_client_payment_proto_EnvelopeContent_reason_tag 4
#define io_libralink_client_payment_proto_EnvelopeContent_envelope_tag 5
#define io_libralink_client_payment_proto_EnvelopeContent_errorResponse_tag 6
#define io_libralink_client_payment_proto_EnvelopeContent_processingFee_tag 7
#define io_libralink_client_payment_proto_EnvelopeContent_surchargeRequest_tag 8
#define io_libralink_client_payment_proto_EnvelopeContent_paymentRequest_tag 9
#define io_libralink_client_payment_proto_EnvelopeContent_check_tag 10
#define io_libralink_client_payment_proto_EnvelopeContent_getBalanceRequest_tag 11
#define io_libralink_client_payment_proto_EnvelopeContent_getBalanceResponse_tag 12
#define io_libralink_client_payment_proto_EnvelopeContent_depositRequest_tag 13
#define io_libralink_client_payment_proto_EnvelopeContent_depositResponse_tag 14
#define io_libralink_client_payment_proto_EnvelopeContent_getProcessorsRequest_tag 15
#define io_libralink_client_payment_proto_EnvelopeContent_getProcessorsResponse_tag 16
#define io_libralink_client_payment_proto_EnvelopeContent_registerKeyRequest_tag 17
#define io_libralink_client_payment_proto_EnvelopeContent_registerKeyResponse_tag 18
#define io_libralink_client_payment_proto_EnvelopeContent_sharePayerDetails_tag 19
#define io_libralink_client_payment_proto_Envelope_id_tag 1
#define io_libralink_client_payment_proto_Envelope_content_tag 2
#define io_libralink_client_payment_proto_Envelope_sig_tag 3
#define io_libralink_client_payment_proto_ProcessingFee_feeType_tag 1
#define io_libralink_client_payment_proto_ProcessingFee_amount_tag 2
#define io_libralink_client_payment_proto_ProcessingFee_intermediary_tag 3
#define io_libralink_client_payment_proto_ProcessingFee_envelope_tag 4
#define io_libralink_client_payment_proto_PaymentRequest_amount_tag 1
#define io_libralink_client_payment_proto_PaymentRequest_from_tag 2
#define io_libralink_client_payment_proto_PaymentRequest_fromProc_tag 3
#define io_libralink_client_payment_proto_PaymentRequest_to_tag 4
#define io_libralink_client_payment_proto_PaymentRequest_toProc_tag 5
#define io_libralink_client_payment_proto_PaymentRequest_currency_tag 6
#define io_libralink_client_payment_proto_PaymentRequest_created_at_tag 7
#define io_libralink_client_payment_proto_PaymentRequest_note_tag 8
#define io_libralink_client_payment_proto_PaymentRequest_correlationId_tag 9
#define io_libralink_client_payment_proto_SurchargeRequest_amount_tag 1
#define io_libralink_client_payment_proto_SurchargeRequest_to_tag 2
#define io_libralink_client_payment_proto_SurchargeRequest_toProc_tag 3
#define io_libralink_client_payment_proto_SurchargeRequest_note_tag 4
#define io_libralink_client_payment_proto_SurchargeRequest_envelope_tag 5
#define io_libralink_client_payment_proto_ECheckSplit_amount_tag 1
#define io_libralink_client_payment_proto_ECheckSplit_to_tag 2
#define io_libralink_client_payment_proto_ECheckSplit_toProc_tag 3
#define io_libralink_client_payment_proto_ECheck_faceAmount_tag 1
#define io_libralink_client_payment_proto_ECheck_currency_tag 2
#define io_libralink_client_payment_proto_ECheck_from_tag 3
#define io_libralink_client_payment_proto_ECheck_fromProc_tag 4
#define io_libralink_client_payment_proto_ECheck_to_tag 5
#define io_libralink_client_payment_proto_ECheck_toProc_tag 6
#define io_libralink_client_payment_proto_ECheck_splits_tag 7
#define io_libralink_client_payment_proto_ECheck_createdAt_tag 8
#define io_libralink_client_payment_proto_ECheck_expiresAt_tag 9
#define io_libralink_client_payment_proto_ECheck_note_tag 10
#define io_libralink_client_payment_proto_ECheck_correlationId_tag 11
#define io_libralink_client_payment_proto_GetBalanceRequest_address_tag 1
#define io_libralink_client_payment_proto_GetBalanceResponse_address_tag 1
#define io_libralink_client_payment_proto_GetBalanceResponse_available_tag 2
#define io_libralink_client_payment_proto_GetBalanceResponse_pending_tag 3
#define io_libralink_client_payment_proto_DepositRequest_checkEnvelope_tag 1
#define io_libralink_client_payment_proto_DepositRequest_requestEnvelopes_tag 2
#define io_libralink_client_payment_proto_DepositResponse_checkEnvelopeId_tag 1
#define io_libralink_client_payment_proto_DepositResponse_requestEnvelopeIds_tag 2
#define io_libralink_client_payment_proto_RegisterKeyRequest_address_tag 1
#define io_libralink_client_payment_proto_RegisterKeyRequest_pubKey_tag 2
#define io_libralink_client_payment_proto_RegisterKeyRequest_algorithm_tag 3
#define io_libralink_client_payment_proto_RegisterKeyRequest_confirmationId_tag 4
#define io_libralink_client_payment_proto_RegisterKeyRequest_hash_tag 5
#define io_libralink_client_payment_proto_RegisterKeyResponse_address_tag 1
#define io_libralink_client_payment_proto_GetProcessorsRequest_address_tag 1
#define io_libralink_client_payment_proto_ProcessorDetails_address_tag 1
#define io_libralink_client_payment_proto_GetProcessorsResponse_processors_tag 1
#define io_libralink_client_payment_proto_ErrorResponse_code_tag 1
#define io_libralink_client_payment_proto_ErrorResponse_message_tag 2
#define io_libralink_client_payment_proto_SharePayerDetails_challenge_tag 1
#define io_libralink_client_payment_proto_SharePayerDetails_from_tag 2
#define io_libralink_client_payment_proto_SharePayerDetails_fromProc_tag 3

/* Struct field encoding specification for nanopb */
#define io_libralink_client_payment_proto_Envelope_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   id,                1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  content,           2) \
X(a, CALLBACK, SINGULAR, STRING,   sig,               3)
#define io_libralink_client_payment_proto_Envelope_CALLBACK pb_default_field_callback
#define io_libralink_client_payment_proto_Envelope_DEFAULT NULL
#define io_libralink_client_payment_proto_Envelope_content_MSGTYPE io_libralink_client_payment_proto_EnvelopeContent

#define io_libralink_client_payment_proto_EnvelopeContent_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   address,           1) \
X(a, CALLBACK, SINGULAR, STRING,   pubKey,            2) \
X(a, CALLBACK, SINGULAR, STRING,   algorithm,         3) \
X(a, CALLBACK, SINGULAR, UENUM,    reason,            4) \
X(a, CALLBACK, ONEOF,    MESSAGE,  (entity,envelope,entity.envelope),   5) \
X(a, CALLBACK, ONEOF,    MESSAGE,  (entity,errorResponse,entity.errorResponse),   6) \
X(a, CALLBACK, ONEOF,    MESSAGE,  (entity,processingFee,entity.processingFee),   7) \
X(a, CALLBACK, ONEOF,    MESSAGE,  (entity,surchargeRequest,entity.surchargeRequest),   8) \
X(a, CALLBACK, ONEOF,    MESSAGE,  (entity,paymentRequest,entity.paymentRequest),   9) \
X(a, CALLBACK, ONEOF,    MESSAGE,  (entity,check,entity.check),  10) \
X(a, CALLBACK, ONEOF,    MESSAGE,  (entity,getBalanceRequest,entity.getBalanceRequest),  11) \
X(a, CALLBACK, ONEOF,    MESSAGE,  (entity,getBalanceResponse,entity.getBalanceResponse),  12) \
X(a, CALLBACK, ONEOF,    MESSAGE,  (entity,depositRequest,entity.depositRequest),  13) \
X(a, CALLBACK, ONEOF,    MESSAGE,  (entity,depositResponse,entity.depositResponse),  14) \
X(a, CALLBACK, ONEOF,    MESSAGE,  (entity,getProcessorsRequest,entity.getProcessorsRequest),  15) \
X(a, CALLBACK, ONEOF,    MESSAGE,  (entity,getProcessorsResponse,entity.getProcessorsResponse),  16) \
X(a, CALLBACK, ONEOF,    MESSAGE,  (entity,registerKeyRequest,entity.registerKeyRequest),  17) \
X(a, CALLBACK, ONEOF,    MESSAGE,  (entity,registerKeyResponse,entity.registerKeyResponse),  18) \
X(a, CALLBACK, ONEOF,    MESSAGE,  (entity,sharePayerDetails,entity.sharePayerDetails),  19)
#define io_libralink_client_payment_proto_EnvelopeContent_CALLBACK pb_default_field_callback
#define io_libralink_client_payment_proto_EnvelopeContent_DEFAULT NULL
#define io_libralink_client_payment_proto_EnvelopeContent_entity_envelope_MSGTYPE io_libralink_client_payment_proto_Envelope
#define io_libralink_client_payment_proto_EnvelopeContent_entity_errorResponse_MSGTYPE io_libralink_client_payment_proto_ErrorResponse
#define io_libralink_client_payment_proto_EnvelopeContent_entity_processingFee_MSGTYPE io_libralink_client_payment_proto_ProcessingFee
#define io_libralink_client_payment_proto_EnvelopeContent_entity_surchargeRequest_MSGTYPE io_libralink_client_payment_proto_SurchargeRequest
#define io_libralink_client_payment_proto_EnvelopeContent_entity_paymentRequest_MSGTYPE io_libralink_client_payment_proto_PaymentRequest
#define io_libralink_client_payment_proto_EnvelopeContent_entity_check_MSGTYPE io_libralink_client_payment_proto_ECheck
#define io_libralink_client_payment_proto_EnvelopeContent_entity_getBalanceRequest_MSGTYPE io_libralink_client_payment_proto_GetBalanceRequest
#define io_libralink_client_payment_proto_EnvelopeContent_entity_getBalanceResponse_MSGTYPE io_libralink_client_payment_proto_GetBalanceResponse
#define io_libralink_client_payment_proto_EnvelopeContent_entity_depositRequest_MSGTYPE io_libralink_client_payment_proto_DepositRequest
#define io_libralink_client_payment_proto_EnvelopeContent_entity_depositResponse_MSGTYPE io_libralink_client_payment_proto_DepositResponse
#define io_libralink_client_payment_proto_EnvelopeContent_entity_getProcessorsRequest_MSGTYPE io_libralink_client_payment_proto_GetProcessorsRequest
#define io_libralink_client_payment_proto_EnvelopeContent_entity_getProcessorsResponse_MSGTYPE io_libralink_client_payment_proto_GetProcessorsResponse
#define io_libralink_client_payment_proto_EnvelopeContent_entity_registerKeyRequest_MSGTYPE io_libralink_client_payment_proto_RegisterKeyRequest
#define io_libralink_client_payment_proto_EnvelopeContent_entity_registerKeyResponse_MSGTYPE io_libralink_client_payment_proto_RegisterKeyResponse
#define io_libralink_client_payment_proto_EnvelopeContent_entity_sharePayerDetails_MSGTYPE io_libralink_client_payment_proto_SharePayerDetails

#define io_libralink_client_payment_proto_ProcessingFee_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   feeType,           1) \
X(a, CALLBACK, SINGULAR, STRING,   amount,            2) \
X(a, CALLBACK, SINGULAR, STRING,   intermediary,      3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  envelope,          4)
#define io_libralink_client_payment_proto_ProcessingFee_CALLBACK pb_default_field_callback
#define io_libralink_client_payment_proto_ProcessingFee_DEFAULT NULL
#define io_libralink_client_payment_proto_ProcessingFee_envelope_MSGTYPE io_libralink_client_payment_proto_Envelope

#define io_libralink_client_payment_proto_PaymentRequest_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   amount,            1) \
X(a, CALLBACK, SINGULAR, STRING,   from,              2) \
X(a, CALLBACK, SINGULAR, STRING,   fromProc,          3) \
X(a, CALLBACK, SINGULAR, STRING,   to,                4) \
X(a, CALLBACK, SINGULAR, STRING,   toProc,            5) \
X(a, CALLBACK, SINGULAR, STRING,   currency,          6) \
X(a, STATIC,   SINGULAR, INT64,    created_at,        7) \
X(a, CALLBACK, SINGULAR, STRING,   note,              8) \
X(a, CALLBACK, SINGULAR, STRING,   correlationId,     9)
#define io_libralink_client_payment_proto_PaymentRequest_CALLBACK pb_default_field_callback
#define io_libralink_client_payment_proto_PaymentRequest_DEFAULT NULL

#define io_libralink_client_payment_proto_SurchargeRequest_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   amount,            1) \
X(a, CALLBACK, SINGULAR, STRING,   to,                2) \
X(a, CALLBACK, SINGULAR, STRING,   toProc,            3) \
X(a, CALLBACK, SINGULAR, STRING,   note,              4) \
X(a, STATIC,   OPTIONAL, MESSAGE,  envelope,          5)
#define io_libralink_client_payment_proto_SurchargeRequest_CALLBACK pb_default_field_callback
#define io_libralink_client_payment_proto_SurchargeRequest_DEFAULT NULL
#define io_libralink_client_payment_proto_SurchargeRequest_envelope_MSGTYPE io_libralink_client_payment_proto_Envelope

#define io_libralink_client_payment_proto_ECheckSplit_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   amount,            1) \
X(a, CALLBACK, SINGULAR, STRING,   to,                2) \
X(a, CALLBACK, SINGULAR, STRING,   toProc,            3)
#define io_libralink_client_payment_proto_ECheckSplit_CALLBACK pb_default_field_callback
#define io_libralink_client_payment_proto_ECheckSplit_DEFAULT NULL

#define io_libralink_client_payment_proto_ECheck_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   faceAmount,        1) \
X(a, CALLBACK, SINGULAR, STRING,   currency,          2) \
X(a, CALLBACK, SINGULAR, STRING,   from,              3) \
X(a, CALLBACK, SINGULAR, STRING,   fromProc,          4) \
X(a, CALLBACK, SINGULAR, STRING,   to,                5) \
X(a, CALLBACK, SINGULAR, STRING,   toProc,            6) \
X(a, CALLBACK, REPEATED, MESSAGE,  splits,            7) \
X(a, STATIC,   SINGULAR, INT64,    createdAt,         8) \
X(a, STATIC,   SINGULAR, INT64,    expiresAt,         9) \
X(a, CALLBACK, SINGULAR, STRING,   note,             10) \
X(a, CALLBACK, SINGULAR, STRING,   correlationId,    11)
#define io_libralink_client_payment_proto_ECheck_CALLBACK pb_default_field_callback
#define io_libralink_client_payment_proto_ECheck_DEFAULT NULL
#define io_libralink_client_payment_proto_ECheck_splits_MSGTYPE io_libralink_client_payment_proto_ECheckSplit

#define io_libralink_client_payment_proto_GetBalanceRequest_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   address,           1)
#define io_libralink_client_payment_proto_GetBalanceRequest_CALLBACK pb_default_field_callback
#define io_libralink_client_payment_proto_GetBalanceRequest_DEFAULT NULL

#define io_libralink_client_payment_proto_GetBalanceResponse_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   address,           1) \
X(a, CALLBACK, SINGULAR, STRING,   available,         2) \
X(a, CALLBACK, SINGULAR, STRING,   pending,           3)
#define io_libralink_client_payment_proto_GetBalanceResponse_CALLBACK pb_default_field_callback
#define io_libralink_client_payment_proto_GetBalanceResponse_DEFAULT NULL

#define io_libralink_client_payment_proto_DepositRequest_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  checkEnvelope,     1) \
X(a, CALLBACK, REPEATED, MESSAGE,  requestEnvelopes,   2)
#define io_libralink_client_payment_proto_DepositRequest_CALLBACK pb_default_field_callback
#define io_libralink_client_payment_proto_DepositRequest_DEFAULT NULL
#define io_libralink_client_payment_proto_DepositRequest_checkEnvelope_MSGTYPE io_libralink_client_payment_proto_Envelope
#define io_libralink_client_payment_proto_DepositRequest_requestEnvelopes_MSGTYPE io_libralink_client_payment_proto_Envelope

#define io_libralink_client_payment_proto_DepositResponse_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   checkEnvelopeId,   1) \
X(a, CALLBACK, REPEATED, STRING,   requestEnvelopeIds,   2)
#define io_libralink_client_payment_proto_DepositResponse_CALLBACK pb_default_field_callback
#define io_libralink_client_payment_proto_DepositResponse_DEFAULT NULL

#define io_libralink_client_payment_proto_RegisterKeyRequest_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   address,           1) \
X(a, CALLBACK, SINGULAR, STRING,   pubKey,            2) \
X(a, CALLBACK, SINGULAR, STRING,   algorithm,         3) \
X(a, CALLBACK, SINGULAR, STRING,   confirmationId,    4) \
X(a, CALLBACK, SINGULAR, STRING,   hash,              5)
#define io_libralink_client_payment_proto_RegisterKeyRequest_CALLBACK pb_default_field_callback
#define io_libralink_client_payment_proto_RegisterKeyRequest_DEFAULT NULL

#define io_libralink_client_payment_proto_RegisterKeyResponse_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   address,           1)
#define io_libralink_client_payment_proto_RegisterKeyResponse_CALLBACK pb_default_field_callback
#define io_libralink_client_payment_proto_RegisterKeyResponse_DEFAULT NULL

#define io_libralink_client_payment_proto_GetProcessorsRequest_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   address,           1)
#define io_libralink_client_payment_proto_GetProcessorsRequest_CALLBACK pb_default_field_callback
#define io_libralink_client_payment_proto_GetProcessorsRequest_DEFAULT NULL

#define io_libralink_client_payment_proto_ProcessorDetails_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   address,           1)
#define io_libralink_client_payment_proto_ProcessorDetails_CALLBACK pb_default_field_callback
#define io_libralink_client_payment_proto_ProcessorDetails_DEFAULT NULL

#define io_libralink_client_payment_proto_GetProcessorsResponse_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  processors,        1)
#define io_libralink_client_payment_proto_GetProcessorsResponse_CALLBACK pb_default_field_callback
#define io_libralink_client_payment_proto_GetProcessorsResponse_DEFAULT NULL
#define io_libralink_client_payment_proto_GetProcessorsResponse_processors_MSGTYPE io_libralink_client_payment_proto_ProcessorDetails

#define io_libralink_client_payment_proto_ErrorResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    code,              1) \
X(a, CALLBACK, SINGULAR, STRING,   message,           2)
#define io_libralink_client_payment_proto_ErrorResponse_CALLBACK pb_default_field_callback
#define io_libralink_client_payment_proto_ErrorResponse_DEFAULT NULL

#define io_libralink_client_payment_proto_SharePayerDetails_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   challenge,         1) \
X(a, CALLBACK, SINGULAR, STRING,   from,              2) \
X(a, CALLBACK, SINGULAR, STRING,   fromProc,          3)
#define io_libralink_client_payment_proto_SharePayerDetails_CALLBACK pb_default_field_callback
#define io_libralink_client_payment_proto_SharePayerDetails_DEFAULT NULL

extern const pb_msgdesc_t io_libralink_client_payment_proto_Envelope_msg;
extern const pb_msgdesc_t io_libralink_client_payment_proto_EnvelopeContent_msg;
extern const pb_msgdesc_t io_libralink_client_payment_proto_ProcessingFee_msg;
extern const pb_msgdesc_t io_libralink_client_payment_proto_PaymentRequest_msg;
extern const pb_msgdesc_t io_libralink_client_payment_proto_SurchargeRequest_msg;
extern const pb_msgdesc_t io_libralink_client_payment_proto_ECheckSplit_msg;
extern const pb_msgdesc_t io_libralink_client_payment_proto_ECheck_msg;
extern const pb_msgdesc_t io_libralink_client_payment_proto_GetBalanceRequest_msg;
extern const pb_msgdesc_t io_libralink_client_payment_proto_GetBalanceResponse_msg;
extern const pb_msgdesc_t io_libralink_client_payment_proto_DepositRequest_msg;
extern const pb_msgdesc_t io_libralink_client_payment_proto_DepositResponse_msg;
extern const pb_msgdesc_t io_libralink_client_payment_proto_RegisterKeyRequest_msg;
extern const pb_msgdesc_t io_libralink_client_payment_proto_RegisterKeyResponse_msg;
extern const pb_msgdesc_t io_libralink_client_payment_proto_GetProcessorsRequest_msg;
extern const pb_msgdesc_t io_libralink_client_payment_proto_ProcessorDetails_msg;
extern const pb_msgdesc_t io_libralink_client_payment_proto_GetProcessorsResponse_msg;
extern const pb_msgdesc_t io_libralink_client_payment_proto_ErrorResponse_msg;
extern const pb_msgdesc_t io_libralink_client_payment_proto_SharePayerDetails_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define io_libralink_client_payment_proto_Envelope_fields &io_libralink_client_payment_proto_Envelope_msg
#define io_libralink_client_payment_proto_EnvelopeContent_fields &io_libralink_client_payment_proto_EnvelopeContent_msg
#define io_libralink_client_payment_proto_ProcessingFee_fields &io_libralink_client_payment_proto_ProcessingFee_msg
#define io_libralink_client_payment_proto_PaymentRequest_fields &io_libralink_client_payment_proto_PaymentRequest_msg
#define io_libralink_client_payment_proto_SurchargeRequest_fields &io_libralink_client_payment_proto_SurchargeRequest_msg
#define io_libralink_client_payment_proto_ECheckSplit_fields &io_libralink_client_payment_proto_ECheckSplit_msg
#define io_libralink_client_payment_proto_ECheck_fields &io_libralink_client_payment_proto_ECheck_msg
#define io_libralink_client_payment_proto_GetBalanceRequest_fields &io_libralink_client_payment_proto_GetBalanceRequest_msg
#define io_libralink_client_payment_proto_GetBalanceResponse_fields &io_libralink_client_payment_proto_GetBalanceResponse_msg
#define io_libralink_client_payment_proto_DepositRequest_fields &io_libralink_client_payment_proto_DepositRequest_msg
#define io_libralink_client_payment_proto_DepositResponse_fields &io_libralink_client_payment_proto_DepositResponse_msg
#define io_libralink_client_payment_proto_RegisterKeyRequest_fields &io_libralink_client_payment_proto_RegisterKeyRequest_msg
#define io_libralink_client_payment_proto_RegisterKeyResponse_fields &io_libralink_client_payment_proto_RegisterKeyResponse_msg
#define io_libralink_client_payment_proto_GetProcessorsRequest_fields &io_libralink_client_payment_proto_GetProcessorsRequest_msg
#define io_libralink_client_payment_proto_ProcessorDetails_fields &io_libralink_client_payment_proto_ProcessorDetails_msg
#define io_libralink_client_payment_proto_GetProcessorsResponse_fields &io_libralink_client_payment_proto_GetProcessorsResponse_msg
#define io_libralink_client_payment_proto_ErrorResponse_fields &io_libralink_client_payment_proto_ErrorResponse_msg
#define io_libralink_client_payment_proto_SharePayerDetails_fields &io_libralink_client_payment_proto_SharePayerDetails_msg

/* Maximum encoded size of messages (where known) */
/* io_libralink_client_payment_proto_Envelope_size depends on runtime parameters */
/* io_libralink_client_payment_proto_EnvelopeContent_size depends on runtime parameters */
/* io_libralink_client_payment_proto_ProcessingFee_size depends on runtime parameters */
/* io_libralink_client_payment_proto_PaymentRequest_size depends on runtime parameters */
/* io_libralink_client_payment_proto_SurchargeRequest_size depends on runtime parameters */
/* io_libralink_client_payment_proto_ECheckSplit_size depends on runtime parameters */
/* io_libralink_client_payment_proto_ECheck_size depends on runtime parameters */
/* io_libralink_client_payment_proto_GetBalanceRequest_size depends on runtime parameters */
/* io_libralink_client_payment_proto_GetBalanceResponse_size depends on runtime parameters */
/* io_libralink_client_payment_proto_DepositRequest_size depends on runtime parameters */
/* io_libralink_client_payment_proto_DepositResponse_size depends on runtime parameters */
/* io_libralink_client_payment_proto_RegisterKeyRequest_size depends on runtime parameters */
/* io_libralink_client_payment_proto_RegisterKeyResponse_size depends on runtime parameters */
/* io_libralink_client_payment_proto_GetProcessorsRequest_size depends on runtime parameters */
/* io_libralink_client_payment_proto_ProcessorDetails_size depends on runtime parameters */
/* io_libralink_client_payment_proto_GetProcessorsResponse_size depends on runtime parameters */
/* io_libralink_client_payment_proto_ErrorResponse_size depends on runtime parameters */
/* io_libralink_client_payment_proto_SharePayerDetails_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
